// <auto-generated />
using System;
using Hub.Service.Catalago.Infra.Data.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hub.Service.Catalago.Infra.Data.EF.Migrations
{
    [DbContext(typeof(FornecedorContext))]
    [Migration("20210727142842_002")]
    partial class _002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Hub.Service.Catalago.Domain.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("nome");

                    b.Property<Guid>("ProfissaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("profissao_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfissaoId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Hub.Service.Catalago.Domain.Profissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Profissoes");
                });

            modelBuilder.Entity("Hub.Service.Catalago.Domain.Fornecedor", b =>
                {
                    b.HasOne("Hub.Service.Catalago.Domain.Profissao", "Profissao")
                        .WithMany("Fornecedores")
                        .HasForeignKey("ProfissaoId")
                        .IsRequired();

                    b.Navigation("Profissao");
                });

            modelBuilder.Entity("Hub.Service.Catalago.Domain.Profissao", b =>
                {
                    b.Navigation("Fornecedores");
                });
#pragma warning restore 612, 618
        }
    }
}
